name: Testing on updates main
on:
  push:
    branches:
      - 'main'
defaults:
  run:
    working-directory: lavanda-automated-download-films
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 15
        uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'adopt'
      - name: Build Maven
        run: mvn test
